---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$(whoami)/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R pof $DEPLOYPATH
    - /bin/cp -R loans $DEPLOYPATH
    - /bin/cp -R partners $DEPLOYPATH
    - /bin/cp -R contact $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
